# Naive Bayes

### Model
#### $P(y|X)=\frac{P(X|y)P(y)}{P(X)}$

if you have a lot of variables: <br>
#### $P(y|x_1, ..., x_n)=\frac{P(x_1|y)P(x_2|y)...P(x_n|y)P(y)}{P(x_1)P(x_2)...P(x_n)}$

Naive Bayes is to use variable X to classify target y based on comparasion of probability of being target 1, target 2, target n

**Step**
1. separate the dataset by target
2. calculate the probability of each target: $P(Y)$
3. for loop each target group:
    * sum up the frequency for each unique word
    * calculate the probability of each word in the target group, **remark: it is $P(X|y)$, conditional prob of x given by target y**
    
Now, we have $P(Y)$, $P(X|y)$ and P(X)<br>
**Input new data** <br>
for loop each target group:
1. multiple the conditional probability for the input data: $P(y|x_1, ..., x_n)=\frac{P(x_1|y)P(x_2|y)...P(x_n|y)P(y)}{P(x_1)P(x_2)...P(x_n)}$
2. compare probability (likelihood) and assign the target with highest prob to the input data

In [26]:
import pandas as pd
import numpy as np

In [27]:
def loadDataSet():
    postingList=[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
                 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
                 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
                 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
                 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
                 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]
    classVec = np.array([0,1,0,1,0,1])    #1 is abusive, 0 not
    return postingList, classVec

In [28]:
postingList,listClasses = loadDataSet()

In [29]:
postingList

[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]

In [30]:
listClasses

array([0, 1, 0, 1, 0, 1])

In [31]:
# extract unique text
def createVocabList(dataSet):
    vocab_set = []
    for post in dataSet:
        vocab_set += post
    return list(set(vocab_set))

In [32]:
vocabList = createVocabList(postingList)
print(vocabList)

['licks', 'take', 'mr', 'not', 'ate', 'maybe', 'I', 'quit', 'worthless', 'park', 'to', 'love', 'steak', 'dog', 'stop', 'posting', 'garbage', 'has', 'food', 'problems', 'buying', 'my', 'how', 'please', 'flea', 'help', 'stupid', 'is', 'so', 'him', 'dalmation', 'cute']


In [33]:
# transfer text into number and 1 = exist, 0 = not exist
def setOfWords2Vec(vocabList, inputSet):
    returnVec = [0]*len(vocabList)
    for word in inputSet:
        if word in vocabList:
            returnVec[vocabList.index(word)] = 1
    return returnVec

In [34]:
print(setOfWords2Vec(vocabList, postingList[0]))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0]


In [25]:
postingList,listClasses = loadDataSet()
vocabList = createVocabList(postingList)
trainMat = []
for doc in postingList:
    trainMat.append(setOfWords2Vec(vocabList, doc))
trainMat = np.array(trainMat)
trainMat[1]

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0])

In [12]:
def Naive_bayes(X, y, y_value):
    X = X + 1
    prob_y = np.count_nonzero(y == y_value) / len(y)    # P(y)
    class_index = np.where(y == y_value)
    group = X[class_index]
    prob_x = group.sum(axis=0) / group.sum()    # P(X|y)
    return prob_x, prob_y

In [13]:
for y_value in np.unique(listClasses):
    prob_x, prob_y = Naive_bayes(trainMat, listClasses, y_value)
prob_x, prob_y

(array([0.02608696, 0.03478261, 0.02608696, 0.03478261, 0.02608696,
        0.03478261, 0.02608696, 0.03478261, 0.04347826, 0.03478261,
        0.03478261, 0.02608696, 0.02608696, 0.04347826, 0.03478261,
        0.03478261, 0.03478261, 0.02608696, 0.03478261, 0.02608696,
        0.03478261, 0.02608696, 0.02608696, 0.02608696, 0.02608696,
        0.02608696, 0.05217391, 0.02608696, 0.02608696, 0.03478261,
        0.02608696, 0.02608696]),
 0.5)