# Neural Network

### Forward propagation
$x_i$ = input layer<br>
$w_i$ = weights<br>
$b$ = bias<br>
$z$ = hidden layer<br>
$f(z)$ = activation<br>

$z = \sum\limits_{i=1}^{n}x_iw_i + b$<br>
Given Sigmoid as activation function: $f(H) = \frac{1}{1+e^{-z}}$

**Remark**<br>
$w_i$ for b is 1<br>
Which activation function to choose depends on the prediction output: number/category<br>
If numerical output, MSE loss function will be used, reLU, linear(Identity) activation will be used.<br>
If categorical output, cross entropy loss function will be used, sigmoid, tanh, softmax (non linear) activation function will be used.



### Back propagation
incrementally tweaking the network’s weights until the lowest possible cost value is obtained.

### Partial derivative for $w_i$: $\frac{\partial C}{\partial w_i} = \frac{\partial C}{\partial \hat{y}} * \frac{\partial \hat{y}}{\partial z} * \frac{\partial z}{\partial w_i}$

1. $\frac{\partial C}{\partial \hat{y}} = \frac{\partial}{\partial \hat{y}}\frac{1}{n}\sum\limits_{i=1}^{n}(y_i-\hat{y_i})^2 = \frac{2}{n}\sum\limits_{1=1}^{n}(y_i-\hat{y_i})$

2. Given $\sigma$ = Sigmoid function (different activation function has different derivative below)

3. $\frac{\partial \hat{y}}{\partial z} = \frac{\partial}{\partial z}\sigma(z) = \sigma(z) * (1-\sigma(z)) $

4. $\frac{\partial z}{\partial w_i} = \frac{\partial}{\partial w_i}\sum\limits_{i=1}^{n}x_iw_i+b = x_i$

### $\frac{\partial C}{\partial w_i} = \frac{2}{n} * \sum\limits_{i=1}^{n}(y_i - \hat{y_i}) * \sigma(z) * (1-\sigma(z)) * x_i$

### Partial derivative for $b$
### $\frac{\partial C}{\partial b} = \frac{2}{n} * \sum\limits_{i=1}^{n}(y_i-\hat{y_i}) * \sigma(z) * (1-\sigma(z))$

# Cost Function
##### MSE = $\frac{1}{n}\sum\limits_{i=1}^{n}(y_i - \hat{y_i})^2$

##### Cross entropy = Sigmoid, etc

### learning algorithm
1. Start with values (often random) for the network parameters (wij weights and bj biases).
2. Take a set of examples of input data and pass them through the network to obtain their prediction.
3. Compare these predictions obtained with the values of expected labels and calculate the loss with them.
4. Perform the backpropagation in order to propagate this loss to each and every one of the parameters that make up the model of the neural network.
5. Use this propagated information to update the parameters of the neural network with the gradient descent in a way that the total loss is reduced and a better model is obtained.
6. Continue iterating in the previous steps until we consider that we have a good model.

In [57]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd
np.set_printoptions(suppress=True)

In [197]:
df = pd.read_csv('housepricedata.csv')
dataset = df.values
X = dataset[:, :-1]
y = dataset[:, -1]
df.head()

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0     8450            7            5          856         2         1   
1     9600            6            8         1262         2         0   
2    11250            7            5          920         2         1   
3     9550            7            5          756         1         0   
4    14260            8            5         1145         2         1   

   BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0             3             8           0         548                 1  
1             3             6           1         460                 1  
2             3             6           1         608                 1  
3             3             7           1         642                 0  
4             4             9           1         836                 1

### Activation function

In [ ]:
def linear(z):
    pass z

In [38]:
def sigmoid(z):
    return 1 / (1+np.exp(-z))

In [43]:
def tanh(z):
    pass

In [2]:
def softmax(X):
    pass

In [40]:
def relu(z):
    return max(0, z)

### Activation

In [31]:
def Dense(a_in, W, b):
    units = W.shape[1]    
    a_out = np.zeros(units)
    
    for i in range(units):
        z = np.dot(W[:, i], a_in) + b[i]    
        a_out = sigmoid(z)
    return a_out

### Number of layer

In [32]:
def Sequential(x, W1, b1, W2, b2):
    a1 = Dense(x, W1, b1)
    a2 = Dense(a1, W2, b2)
    return a2

### Prediction

In [33]:
def Predict(X, W1, b1, W2, b2):
    m = X.shape[0]
    p = np.zeros((m, 1))
    
    for i in range(m):
        p[i, 0] = Sequential(X[i], W1, b1, W2, b2)
    return p

In [184]:
# 2 layers
# 4 nodes
W1 = np.random.rand(10,4)
b1 = np.random.rand(4)

W2 = np.random.rand(10,4)
b2 = np.random.rand(4)

In [187]:
W1, b1, W2, b2

(array([[0.68262706, 0.27487343, 0.56812985, 0.17540847],
        [0.24054411, 0.68411033, 0.1366435 , 0.2521047 ],
        [0.41011058, 0.35421278, 0.98904545, 0.31962824],
        [0.2068564 , 0.36545202, 0.17769844, 0.65540447],
        [0.29881942, 0.6137714 , 0.82158519, 0.41697487],
        [0.46911376, 0.53523226, 0.94424482, 0.19747458],
        [0.72852203, 0.72820681, 0.93687414, 0.82021153],
        [0.91220527, 0.55374311, 0.03603129, 0.01085086],
        [0.55686604, 0.74908935, 0.17052022, 0.52149317],
        [0.85559291, 0.36327194, 0.29514968, 0.20671711]]),
 array([0.54548938, 0.69922207, 0.25943934, 0.04527258]),
 array([[0.39032742, 0.81030861, 0.58444715, 0.34679871],
        [0.38024297, 0.28181382, 0.81334624, 0.45556792],
        [0.27288947, 0.8398318 , 0.70152395, 0.73257836],
        [0.60973088, 0.87689961, 0.09905038, 0.80607732],
        [0.63646229, 0.27516139, 0.18843138, 0.20226076],
        [0.93405638, 0.70144375, 0.70565264, 0.1670798 ],
        [0.0

In [195]:
np.dot(X[1], W1) + b1

array([7221.92820383, 3282.21176423, 5827.90303053, 2614.12772078])